import { Oxygen } from "next/font/google";
import "./globals.css";
import Pinned from "./ketan/Pinned";
import Navbar from "./ketan/Navbar";

const inter = Oxygen({ subsets: ["latin"], weight: ["300", "400", "700"] });

export const metadata = {
  title: "Insightify",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
